on: [push, pull_request, workflow_dispatch]

name: Build

jobs:
  lily58:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:2.4
    name: Build Lily 58
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache west modules
        uses: actions/cache@v2
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('manifest-dir/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: West Init
        run: west init -l config
      - name: West Update
        run: west update
      - name: West Zephyr export
        run: west zephyr-export
      - name: West Build (Lily58 Left)
        run: west build -s zmk/app -b nice_nano -- -DSHIELD=lily58_left -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      - name: Lily58 DTS File
        if: ${{ always() }}
        run: cat -n build/zephyr/nice_nano.dts.pre.tmp
      - name: Lily58 Left Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 lily58_left_nice_nano.uf2
      - name: Archive (Lily58 Left)
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: lily58_left_nice_nano.uf2
      - name: West Build (Lily58 Right)
        run: west build --pristine -s zmk/app -b nice_nano -- -DSHIELD=lily58_right -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"

      - name: Lily58 Right Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 lily58_right_nice_nano.uf2
      - name: Archive (Lily58 Right)
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: lily58_right_nice_nano.uf2
  helix:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:2.5
    name: Build Helix
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache west modules
        uses: actions/cache@v2
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('manifest-dir/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: West Init
        run: west init -l config
      - name: West Update
        run: west update
      - name: West Zephyr export
        run: west zephyr-export
      - name: West Build (Helix Left)
        run: west build -s zmk/app -b nice_nano_v2 -- -DSHIELD=helix_left -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      - name: Helix DTS File
        if: ${{ always() }}
        run: cat -n build/zephyr/nice_nano_v2.dts.pre.tmp
      - name: Helix Left Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 helix_left_nice_nano_v2.uf2
      - name: Archive (Helix Left)
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: helix_left_nice_nano_v2.uf2
      - name: West Build (Helix Right)
        run: west build --pristine -s zmk/app -b nice_nano_v2 -- -DSHIELD=helix_right -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"

      - name: Helix Right Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 helix_right_nice_nano_v2.uf2
      - name: Archive (Helix Right)
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: helix_right_nice_nano_v2.uf2